### ISSUE TITLE
WMP only imports tracks with more than three stars rating

### ISSUE THREAD

**Issue by hans-juergen** [coczero/Last.fm-Scrubbler-WPF#7]
Hi, I just noticed that your app only imports tracks from Windows Media Player which have a 4 or 5 star rating in the database, but leaves out everything with 3 stars which is the default setting. It should probably ignore the ratings completely when importing.

By the way, sorting columns works fine even with my large CSV listening history, thank you.

**Comment by coczero** [comment]
Hi, I just checked this and I can't seem to reproduce this. I gave my tracks a 3 star rating and they imported just fine. Please note that I only display tracks in the Scrubbler that have been played atleast once. Therefore it *might* seem like I ignore 3 star ratings because thats the default for a 0-play track.

**Comment by hans-juergen** [comment]
Yes, you're right, I haven't played many of my media files on this computer, just copied them over from my other one. Now I have enabled the column for play counts which is disabled in the default view, and can see that most of my files have 0 plays here. Thank you for the explanation!

**Comment by coczero** [comment]
Of course, it might make sense to implement some kind of "import" mode that does not need any play counts. With that people could scrobble each track once and fill up their library and get recommendations etc...
