### ISSUE TITLE
"Current Status: Error while scrobbling selected tracks: Cached"

### ISSUE THREAD

**Issue by kirincallinan** [coczero/Last.fm-Scrubbler-WPF#88]
What does this error message mean?

**Comment by coczero** [comment]
It usually means that the scrobbles could not be sent to last.fm (usually due to a connection error)

**Comment by bluemelodypp** [comment]
same problem here
how to solve this?

**Comment by coczero** [comment]
Could you describe how and when you are getting this error?
I've seen this error occur when trying to scrobble more than 3000 tracks per day.

**Comment by ElectricDude01** [comment]
Same here. As for me, I barely scrobble 100 songs per day so it's kinda confusing. If it helps, I've recently changed my Last.fm username, and thus I switched to the new one in the Scrubbler (I can't really remember if this error started happening just after doing so tbh - I logged in the new username earlier this month, but I didn't scrobble anything from this app back then)

**Comment by coczero** [comment]
@ElectricDude01 what scrobbler are you using?

**Comment by ElectricDude01** [comment]
As in the Scrubbler version? Beta 1.22

**Comment by coczero** [comment]
@ElectricDude01 no I meant what type of scrobbler are you using to scrobble the 100 tracks?
Are you scrobbling them in bulk via the csv scrobbler or something else?

**Comment by ElectricDude01** [comment]
Something else. I usually scrobble from my phone (in this case, Scroball) but recently I tried to use desktop scrobblers and none of them is working for me now

**Comment by ElectricDude01** [comment]
@coczero any news yet?

**Comment by coczero** [comment]
@ElectricDude01  Unfortunately not. This seems to be very random.
Some people have no issues at all, some people can't scrobble large amounts and for some it never works. I have no idea why tbh :(

**Comment by ElectricDude01** [comment]
Oof, this is really strange :/ Hopefully there'll be a solution any moment now

**Comment by Aubreyodom** [comment]
I was having this issue. Like another user, I had also just changed my username (as of yesterday), then logged in and tried to scrobble a track and recieved the error. What fixed it on my end was to log into the Last.fm site, then go to settings > applications settings and disconnect the scrubbler. I then went back to the scrubbler, logged out and back in, and the error was resolved. Hope this helps someone.

**Comment by ElectricDude01** [comment]
> I was having this issue. Like another user, I had also just changed my username (as of yesterday), then logged in and tried to scrobble a track and recieved the error. What fixed it on my end was to log into the Last.fm site, then go to settings > applications settings and disconnect the scrubbler. I then went back to the scrubbler, logged out and back in, and the error was resolved. Hope this helps someone.

Thank you so much! It's finally working for me now

**Comment by coczero** [comment]
Interesting, thank you for sharing your solution!
I will close this for now.

**Comment by BotJohn** [comment]
I am currently having the same issue

**Comment by jaredknppr** [comment]
I'm having the same issue but did _not_ change my username; I did update the Scrubbler software to 1.29, but I tried again on 1.27 to see what happened and.... no success. I did file parse uploads for 2 days, 2,600 scrobbles each day, then got the error message on the third doing the uploads all in rapid succession, no more than 5 minutes apart. I deleted the Scrubbler from my list of connected apps on the Last.fm site, I logged out from the Scrubbled and logged back in, I restarted my computer. None of those things worked, and I tried again about 12h after the first failure to see if time helped, and I still got the cache error. I tried a few different upload files, and I also chose a few different days as the upload "timestamp."

Has anyone else come up with a solution for reset or identified an issue that could be behind the cache error? I did verify that the days into which I was trying to upload my scrobbles didn't have more than 400 tracks each that would push me over the daily max, so that can't be my problem either.
